name: Deploy code to GitHub pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: log untrusted output
        run: 
          echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
          echo "untrusted output"
          echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0-8
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: master
          publish_dir: ./
          external_repository: JayesNS/jayesns.github.io
          destination_dir: ./simon-says